### PR TITLE
Projection Lines

### PR DESCRIPTION
**Pull request by brandonbrinkley**
I have added the ability to display a projected trend line on the burndown chart. Several options are available, including the option to show no line at all (default). The projection appears as a dashed line that begins at the end of the actual data line, and extends to either the x-axis or the right side of the chart, depending on the calculation. Options can be selected on the configuration panel.

### CODE REVIEW

**Comment by tomkamphuis** [comment]
Thanks for your pull request, I'll try to review and test it within a week and let you know if it's added to the extension.

**Comment by tomkamphuis** [comment]
Looks like it contains a bug. When you're at the second day of the sprint and you moved some work to done that second day the graph loses it's aggregate of work to do. It becomes a burn-up with the amount of points for that single PBI. So it needs some further development.
But I like the idea so if it's out of the code I would like to introduce it into the plugin.

**Comment by brandonbrinkley** [comment]
I will try to recreate the problem and fix it. Did this only occur on the second day of the sprint? And did it happen with any choice of projection line?

**Comment by tomkamphuis** [comment]
This occurs on all days after that with all project line options. Linear
and last 3 days even plot upwards instead of downwards.

**Comment by brandonbrinkley** [comment]
Ok, I've set up a new sprint in a dummy test project and added some PBIs with points. I set the start date for yesterday, so today is the second day of the sprint. The blue ideal line is flat, I assume because we currently lack data for Day 0, but that's not all that important for the test. Here's what I'm seeing so far:

- The 'Zero' projection line goes to zero as expected.
- The 'Ideal' projection line gets it's slope from the blue ideal line, so at the moment it is (abnormally) horizontal.
- The orange actual line shoots up from 0 points to 27 points between days 0 and 1, so the 'Linear' projection line simply continues that upward trend.
- The 'Last 3 Days' projection looks the same as the Linear projection and will continue to do so until the fourth day (or later, depending on the data).

All of these look as I intended them to look so far. I will burn down some points each day and watch how the projections change.

**Comment by tomkamphuis** [comment]
Please set the startdate of the sprint to the same day as you added the PBI's to the sprint. Due to the way VSO manages these you need to add the points on the first day of the sprint as to have a more normal graph.

**Comment by brandonbrinkley** [comment]
After another day, the projection lines are still being drawn as I expected for them to look. I've actually been using this modified version of the extension on a few projects on our production TFS server for a few weeks now with no issues, and I can't seem to reproduce what you are seeing.

Is the concern that the projection line sometimes has a positive slope? For Ideal and Zero, this should never happen, but for Linear and Last 3 Days it can! These different projection lines are based on feedback from my colleagues. The Ideal projection was preferred by most, based on the assumption that the (blue) Ideal line (and it's slope) is a reasonable estimation of the team's velocity. The Linear and Last 3 Day projections are more appropriate for brand new teams or situations in which the team's behavior or situation in no way represents their normal performance. So, if they have not delivered any value (closed stories) or have only seen a net gain in points, then continuing that pattern of behavior will almost ensure they will not burn down to zero. If they start producing, however, the projection will reflect it. The Last 3 Days projection is more forgiving in this case, whereas the Linear projection is more conservative. Does this make sense?

If you have a screenshot where the Ideal or Zero projection trends upward, it would be helpful.

Oh, and we are still on TFS 2015, but since the existing extension works and all I'm doing here is adding lines based on numbers that either come from the same dataset your code uses or are derived from that dataset, then I would not expect the version to make a difference.

**Comment by tomkamphuis** [comment]
I've found what was wrong and it turned out it hadn't anything to do with your code. I will try to merge your changes into the code base somewhere over the next week if that's ok with you.

**Comment by brandonbrinkley** [comment]
Sounds good to me! Thanks!

**Comment by tomkamphuis** [comment]
I've merged it into my test project and there's still one thing that is wrong. When going to previous sprints the projection line behaves in a peculiar manner. If you want to look at this please do so, otherwise I'll do it a bit later but until a fix this won't be in the next release.

**Pull request merged**
